"""Replace voting with aura points

Revision ID: 3e606eef306f
Revises: 3c82bca0a445
Create Date: 2024-10-05 00:50:30.436876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e606eef306f'
down_revision = '3c82bca0a445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aura_points', sa.Integer(), nullable=True))
        batch_op.drop_column('vote_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('aura_points')

    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vote_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='vote_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='vote_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vote_pkey')
    )
    # ### end Alembic commands ###
